apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins2
  namespace: kube-ops
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: jenkins2.banna.com
    http:
      paths:
      - backend:
          serviceName: jenkins2
          servicePort: 8080
