apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        hosts {
        172.21.40.250 git.banna.com
        172.21.40.250 registry.banna.com
        fallthrough
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-09-18T03:47:03Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "195"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 9d4f9885-3643-41bd-b191-3ad57cd800d5
